### ISSUE TITLE
Compilation on windows

### ISSUE THREAD

**Issue by Delkaspo** [lindenbaum/maven-erlang-plugin#1] opened 2012-06-05 10:14 UTC
Hi,

First of all thank you for this plugin.
It works fine on linux but when I try to compile on a windows this error occurs:

> [erlang:validate]
> 
> [erlang:initialize]
> 
> [erlang:extract-dependencies]
> 
> [erlang:reload-dependencies]
> 
> [erlang:generate-resources]
> 
> [erlang:compile]
> ---
> 
> C O M P I L E R
> ---
> 
> No MIBs to compile.
> Errors:
> - c:UsersDelkaspoDocumentsNetBeansProjectsirtualbrownpaperMiddleWare rcmainrlang    oto.erl:none
>   I/O error
>   ------------------------------------------------------------------------
>   BUILD FAILURE
>   ------------------------------------------------------------------------
>   Total time: 2.438s
>   Finished at: Tue Jun 05 11:52:46 CEST 2012
>   Final Memory: 11M/108M
>   ------------------------------------------------------------------------
>   Failed to execute goal eu.lindenbaum:maven-erlang-plugin:2.2.0:compile (default-compile) on project middleware: Failed to >compile [C:UsersDelkaspoDocumentsNetBeansProjectsirtualbrownpaperMiddleWare rcmainrlang   oto.erl]. -> [Help 1]
> 
> To see the full stack trace of the errors, re-run Maven with the -e switch.
> Re-run Maven using the -X switch to enable full debug logging.
> 
> For more information about the errors and possible solutions, please read the following articles:
> [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> Successfully shut down 'middleware-maven-erlang-plugin-backend@ip-adress'
> ---

It looks like he interprets the backslash of windows.

Thanks for all

**Comment by schlagert** [comment] 2012-06-13 07:29
Thanks for the report. The plug-in is currently developed under Linux and Mac OS only, I'll see if we can borrow some computation time from my collegues' windows machines to reproduce the problem.

**Comment by schlagert** [comment] 2014-10-09 09:57
Hi and huge apologies for not answering such a long time!

You are right, there's some kind of escaping problems in the `.erl` scripts under Windows. Unfortunately, we won't fix this ourself, because we do not actively maintain the plugin anymore.

**Closed as completed** 2016-05-27 14:01 UTC
Labels: bug
